accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
 
    path('user_detail/<int:pk>', UserDetail.as_view(), name='user_detail'),
    path('user_list/', UserList.as_view(), name='user_list'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout, name='logout'),
    path('signup/', Signup.as_view(), name='signup'),
    path('forget_password1/', ForgetPassword1.as_view(), name='forget_password1'),
    path('forget_password2/<str:n_code>', ForgetPassword2.as_view(), name='forget_password2'),
    path('change_password/<str:n_code>', ChangePassword.as_view(), name='change_password'),
  
]

borrows/urls.py
from .views import *
from django.urls import path

app_name = 'borrows'

urlpatterns = [
    path('borrow_list', BorrowList.as_view(),name='borrow_list'),
    path('my_borrow_list', MyBorrowList.as_view(),name='my_borrow_list'),
    path('borrow_book/<int:pk>', BorrowBook.as_view(),name='borrow_book'),
    path('report/<int:id_user>/<int:id_borrow>', Report.as_view(), name="report"),
    path('give_back_book/<int:id_book>', GiveBack.as_view(), name="give_back_book"),
    ]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include("home.urls",namespace='home')),
    path('accounts/',include("accounts.urls",namespace='accounts')),
    path('borrows/',include("borrows.urls",namespace='borrows')),
    path('',include("home.urls",namespace='index')), #  برای وقتی کاربر چیزی نزنه خودکار home لحاظ بشه
    
]

home/urls.py
from .views import *
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('book_list/', BookList.as_view(), name='book_list'),
    path('book_detail/<int:id> ', BookDetail.as_view(), name='book_detail'),
    path('book_create/', BookCreate.as_view(),name='book_create' ),
    ]

borrows/models.py
from datetime import timedelta
from django.db import models
from django.contrib.auth import get_user_model
from home.models import Book
from datetime import datetime


user = get_user_model()


class Borrow(models.Model):
    Borrower = models.ForeignKey(user, on_delete=models.CASCADE, related_name="borrows")
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE, related_name="borrows")
    s_deadline = models.DateTimeField(auto_now_add=True)
    e_deadline = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.e_deadline:
            self.e_deadline = datetime.now() + timedelta(weeks=1)
        super().save(*args, **kwargs)


class Report(models.Model):
    for_borrow = models.ForeignKey(Borrow, on_delete=models.DO_NOTHING, related_name="reports_borrow",null=True,blank=True)
    to_user = models.ForeignKey(user, on_delete=models.DO_NOTHING, related_name="reports_to",null=True,blank=True)
    titel = models.CharField(max_length=40)
    description = models.TextField()
    dete = models.DateTimeField(auto_now_add=True)

borrows/forms.py
from django.forms import ModelForm
from .models import Report


class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = ['titel','description']

borrows/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View

from .forms import ReportForm
from home.models import Book
from borrows.models import Borrow


# قرض گرفتن کتاب
class BorrowBook(LoginRequiredMixin, View):
    def get(self, request, pk):
        book = get_object_or_404(Book, id=pk)
        book.is_available = False
        book.save()
        borrow_id = Borrow.objects.create(Borrower=request.user, book=book).id
        user_id = request.user.id
        context = {'book': book, "borrow_id": borrow_id, "user_id":user_id}
        
        return render(request, template_name="borrows/borrow_book.html", context=context)


# پس دادن کتابی که قرض گرفته شده
class GiveBack(View):
    def get(self, request, id_book):
        book = get_object_or_404(Book, id=id_book)
        book.is_available = True
        book.save()
        return redirect("home:book_detail", id=id_book)


#  لیست همه تراکنش های قرض گرفتن کتاب
class BorrowList(View):
    def get(self, request):
        context = {
            'borrows': Borrow.objects.all(),
            "all": True
        }
        return render(request, 'borrows/borrow_list.html',context=context)
        
        
# لیست تراکنش های قرض گرفتن هایی که خود کاربر انجام داده
class MyBorrowList(LoginRequiredMixin,View):
    def get(self, request):
        context = {
            'borrows': Borrow.objects.filter(Borrower=request.user),
            "all": False
        }
        return render(request, 'borrows/borrow_list.html',context=context)
 
 
# گزارش قرض گیرنده قبلی کتاب
class Report(LoginRequiredMixin, View):
    form_class = ReportForm
    template_name = "form.html"
    cotext = {
        "form_title": "report",
        "form": form_class,
        "Button_text": "submit",
    }
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.cotext)
    
    def post(self, request, id_user, id_borrow, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            rep = form.save(commit=False)
            rep.to_user = get_object_or_404(get_user_model(),  id=id_user)
            rep.for_borrow = get_object_or_404(Borrow, id=id_borrow)
            rep.save()
            messages.success(request, "Your report has been sent", "success")
            return redirect('home:book_list')
        else:
            return render(request, self.template_name, self.cotext)

borrows/templates/borrows/borrow_book.html
{% extends 'base.html' %}

{% block title %}{{ book.name }}{% endblock %}

{% block content %}
<a href="{% url 'borrows:give_back_book' book.id %}" class="btn btn-warning">give back</a>
<h1 >{{ book.name }}</h1>
<p><strong>Author:</strong> {{ book.author }}</p>
<p><strong>Published Date:</strong> {{ book.published }}</p>
<p><strong>Summary:</strong> {{ book.summary }}</p>

    <p class="text-success">You borrowed the book (dedlin: 1 week).</p>


    <p>You can get it from the previous user</p>
    
    <a href="{% url 'accounts:user_detail' user_id %}" class="btn btn-info">Previous user information</a>
    <a href="{% url 'borrows:report' user_id borrow_id %}" class="btn btn-danger">Previous user report</a>

{% endblock %}

borrows/templates/borrows/borrow_list.html
{% extends 'base.html' %}

{% block title %}Borrowed Books{% endblock %}

{% block content %}
<h1>Borrowed Books</h1>
    {% if all %}
        <a href="{% url "borrows:my_borrow_list" %}" class="btn btn-secondary">only me</a>
    {% else %}
        <a href="{% url "borrows:borrow_list" %}" class="btn btn-secondary">all</a>
    {% endif %}
<div class="list-group">
    {% for borrow in borrows %}
    <a href="{% url 'home:book_detail' borrow.book.id %}" class="list-group-item list-group-item-action">
        <h5 class="mb-1">{{ borrow.book.name }}</h5>
        <p class="mb-1">Borrowed by {{ borrow.Borrower.full_name }} until {{ borrow.e_deadline }}</p>
        <small>Borrowed on {{ borrow.s_deadline }}</small>
    </a>
    {% endfor %}
</div>
{% endblock %}