borrows/urls.py
from .views import *
from django.urls import path

app_name = 'borrows'

urlpatterns = [
    path('borrow_list', BorrowList.as_view(),name='borrow_list'),
    path('my_borrow_list', MyBorrowList.as_view(),name='my_borrow_list'),
    path('borrow_book/<int:pk>', BorrowBook.as_view(),name='borrow_book'),
    path('report/<int:id_user>/<int:id_borrow>', Report.as_view(), name="report"),
    path('give_back_book/<int:id_book>', GiveBack.as_view(), name="give_back_book"),
    ]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include("home.urls",namespace='home')),
    path('accounts/',include("accounts.urls",namespace='accounts')),
    path('borrows/',include("borrows.urls",namespace='borrows')),
    path('',include("home.urls",namespace='index')), #  برای وقتی کاربر چیزی نزنه خودکار home لحاظ بشه
    
]

home/urls.py
from .views import *
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('book_list/', BookList.as_view(), name='book_list'),
    path('book_detail/<int:id> ', BookDetail.as_view(), name='book_detail'),
    path('book_create/', BookCreate.as_view(),name='book_create' ),
    ]

home/models.py
from django.db import models
from django.contrib.auth import get_user_model

import accounts.models


class Book(models.Model):
    donator = models.ForeignKey(accounts.models.MyUser, on_delete=models.SET_NULL, null=True, blank=True, related_name="donateds")
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=30)
    published = models.DateTimeField(auto_now_add=True)
    Summary = models.TextField(blank=True,null=True)
    is_available = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name
    
    

home/forms.py
from django.forms import ModelForm
from .models import Book


class AddBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["name","author","Summary"]
    

home/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect

from borrows.models import Borrow
from .models import Book
from .forms import AddBookForm


#  وقتی کاربر فقط آدس سایت رو وارد کنه هدایت میشه به لیست کتاب ها (به عنوان صفحه اصلی)
class Index(View):
    def get(self, request):
        return redirect("home:book_list")


# جزِیات کتاب رو نشون میده (قرض گرفتن کتاب . پس دادن . اطلاعات کاربر قبلی . گزارش کاربر قبلی )
class BookDetail(View):
    def get(self, request, id):
        book = get_object_or_404(Book, id=id)
        context = {"book": book}
        if not book.is_available:
            borrow = Borrow.objects.filter(book=book).last()
            borrower = borrow.Borrower
            if borrower == request.user:
                context["borrow_id"] = borrow.id
                context["user_id"] = borrower.id
                return render(request, template_name="borrows/borrow_book.html", context=context)
            context["current_borrower"] = borrower
        
        return render(request, 'home/book_detail.html', context=context)


# لیست همه کتاب ها
class BookList(View):
    def get(self, request):
        books = Book.objects.all()
        context = {
            "books": books
        }
        return render(request, 'home/book_list.html', context=context)


# اهدا کردن کتاب و اضافه شدن به لیست کتاب ها
class BookCreate(LoginRequiredMixin, View):
    form_class = AddBookForm
    template_name = "form.html"
    
    def get(self, request, *args, **kwargs):
        cotext = {
            "form_title": "Donate Book",
            "form": self.form_class,
            "Button_text": "submit",
        }
        return render(request, self.template_name, cotext)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            nwe_book = form.save(commit=False)
            nwe_book.donator = request.user
            nwe_book.save()
            messages.success(request, "Your success message", "success")
            return redirect('home:book_list')
        else:
            cotext = {
                "form_title": "Donate Book",
                "form": form,
                "Button_text": "submit",
            }
            return render(request, self.template_name, cotext)

home/templates/home/book_detail.html
{% extends 'base.html' %}

{% block title %}{{ book.name }}{% endblock %}

{% block content %}
<h1>{{ book.name }}</h1>
<p><strong>Author:</strong> {{ book.author }}</p>
<p><strong>Published Date:</strong> {{ book.published }}</p>
<p><strong>Summary:</strong> {{ book.Summary }}</p>

<h3>Borrowing Information</h3>
{% if book.is_available %}
    <p class="text-success">This book is available for borrowing.</p>
    <a href="{% url 'borrows:borrow_book' book.id %}" class="btn btn-primary">Borrow this Book</a>
{% else %}
    <p class="text-danger">This book is currently borrowed by {{ current_borrower }} .</p>
{% endif %}
{% endblock %}

home/templates/home/book_list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
<h1>All Books</h1>
<a href="{% url 'home:book_create' %}" class="btn btn-primary mb-3">Add New Book</a>
<div class="list-group">
    {% for book in books %}
    <a href="{% url 'home:book_detail' book.id %}" class="list-group-item list-group-item-action">
        <h5 class="mb-1">{{ book.name }}</h5>
        <p class="mb-1">{{ book.author }}</p>
        <small>{{ book.published|timesince }}</small>
    </a>
    {% endfor %}
</div>
{% endblock %}